[package]
name = "PermaplanT"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
dotenvy = "0.15.0"

[dependencies.diesel]
version = "2.0.2"
features = ["postgres", "r2d2", "chrono", "numeric"]

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[dependencies.bigdecimal]
version = "0.3.0"
features = ["serde"]

[dependencies.chrono]
version = "0.4.23"
features = ["serde"]
