[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }
serde = { version = "1.0.152", features = ["derive"] }
dotenvy = "0.15.0"
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }
