name: Bug report
description: For PermaplanT issues
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest PermaplanT release.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.

  - type: textarea
    attributes:
      label: Describe the Bug
      description: Some short sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce the Problem
      description: Please provide a step by step guide on how to reproduce the problem here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Result
      description: What you would expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Result
      description: What actually happened.
    validations:
      required: true

  - type: input
    attributes:
      label: PermaplanT version
      description: If you're not on release, provide the commit hash
      placeholder: 0.2.1
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: Which OS with which version was used?
      placeholder: Windows 11
    validations:
      required: true

  - type: input
    attributes:
      label: Browser
      description: Which browser in which version was used?
      placeholder: Chrome 114.0.5735.199
    validations:
      required: true

  - type: input
    attributes:
      label: Versions of other relevant software/extensions
      description: Any extensions that are active and might have an impact on the page.
      placeholder: HoverZoom/Adblock/etc..
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info/logs
    validations:
      required: true
